/** 365 frases estoicas (índice 0 = 1 de enero). */
export interface StoicQuote {
  author: string;
  text: string;
}

export const STOIC_QUOTES: readonly StoicQuote[] = [
  { author: "Marco Aurelio", text: "La felicidad de tu vida depende de la calidad de tus pensamientos." },
  { author: "Marco Aurelio", text: "No actúes como si fueras a vivir diez mil años. La muerte pende sobre ti." },
  { author: "Marco Aurelio", text: "Piensa en ti mismo como muerto. Has vivido tu vida. Ahora toma lo que queda y vívelo bien." },
  { author: "Marco Aurelio", text: "La mejor venganza es no ser como tu enemigo." },
  { author: "Marco Aurelio", text: "Si no es correcto, no lo hagas; si no es verdad, no lo digas." },
  { author: "Marco Aurelio", text: "Acepta sin orgullo, renuncia sin apego." },
  { author: "Marco Aurelio", text: "Lo que no es bueno para la colmena, no es bueno para la abeja." },
  { author: "Marco Aurelio", text: "El tiempo es un río de acontecimientos que se llevan todo a su paso." },
  { author: "Marco Aurelio", text: "Nada le sucede a nadie que no esté preparado por naturaleza para soportarlo." },
  { author: "Marco Aurelio", text: "Cuando despiertes, di: hoy me encontraré con el entrometido, el ingrato, el insolente." },
  { author: "Marco Aurelio", text: "No desperdicies el resto de tu vida en imaginaciones sobre los demás." },
  { author: "Marco Aurelio", text: "La muerte sonríe a todos; lo único que puede hacer un hombre es sonreírle de vuelta." },
  { author: "Marco Aurelio", text: "Un hombre recto no tiene por qué temer ni a la muerte ni al dolor." },
  { author: "Marco Aurelio", text: "La gloria eterna es una vanidad; en poco tiempo todo se olvida." },
  { author: "Marco Aurelio", text: "Retírate a ti mismo. El centro racional es una fortaleza inexpugnable." },
  { author: "Marco Aurelio", text: "Ama solo lo que te ocurre y te es hilado. ¿Qué puede ser más adecuado?" },
  { author: "Marco Aurelio", text: "La obstinación en el error es un segundo error." },
  { author: "Marco Aurelio", text: "No te dejes arrastrar por la impresión; examínala." },
  { author: "Marco Aurelio", text: "Haz cada acto de tu vida como si fuera el último." },
  { author: "Marco Aurelio", text: "La maldad de otro no puede aferrarse a tu mente a menos que tú lo permitas." },
  { author: "Séneca", text: "No es que tengamos poco tiempo, sino que perdemos mucho." },
  { author: "Séneca", text: "Mientras esperamos vivir, la vida pasa." },
  { author: "Séneca", text: "La vida, si sabes usarla, es larga." },
  { author: "Séneca", text: "Comienza a vivir de una vez y cuenta cada día como una vida completa." },
  { author: "Séneca", text: "El que sufre antes de lo necesario, sufre más de lo necesario." },
  { author: "Séneca", text: "No es el hombre que tiene poco, sino el que ansía más, el que es pobre." },
  { author: "Séneca", text: "A veces incluso vivir es un acto de coraje." },
  { author: "Séneca", text: "Si un hombre no sabe hacia qué puerto navega, ningún viento le es favorable." },
  { author: "Séneca", text: "La dificultad fortalece la mente, como el trabajo fortalece el cuerpo." },
  { author: "Séneca", text: "Espera lo mejor, prepárate para lo peor y acepta lo que venga." },
  { author: "Séneca", text: "La ira es un veneno que bebes esperando que el otro muera." },
  { author: "Séneca", text: "No hay viento favorable para el que no sabe a dónde va." },
  { author: "Séneca", text: "Retira el deseo de lo que no es tuyo y serás libre." },
  { author: "Séneca", text: "El sabio no es sorprendido por la fortuna: la ha anticipado en su mente." },
  { author: "Séneca", text: "Vive de inmediato. La postergación es el ladrón del tiempo." },
  { author: "Séneca", text: "Aprende a sentir alegría, no solo alivio cuando cesa el mal." },
  { author: "Séneca", text: "Una mente que se inquieta por el futuro es miserable." },
  { author: "Séneca", text: "No hay cosa más digna que un alma que se domina a sí misma." },
  { author: "Séneca", text: "La verdadera felicidad es disfrutar el presente sin depender ansiosa del futuro." },
  { author: "Séneca", text: "Prefiere la calidad de los días a su mera cantidad." },
  { author: "Epicteto", text: "No son las cosas las que nos perturban, sino nuestras opiniones sobre ellas." },
  { author: "Epicteto", text: "Primero di a ti mismo qué quieres ser; luego haz lo que tengas que hacer." },
  { author: "Epicteto", text: "La riqueza no consiste en tener grandes posesiones, sino en tener pocas necesidades." },
  { author: "Epicteto", text: "No pretendas que los acontecimientos ocurran como quieres; desea que ocurran como ocurren." },
  { author: "Epicteto", text: "Si quieres mejorar, conténtate con ser considerado ignorante en lo que no sabes." },
  { author: "Epicteto", text: "Nadie es libre si no es dueño de sí mismo." },
  { author: "Epicteto", text: "No expliques tu filosofía; encárnala." },
  { author: "Epicteto", text: "Elige no ser dañado y no sentirás daño." },
  { author: "Epicteto", text: "Solo hay un camino hacia la felicidad: dejar de preocuparse por lo que está fuera de tu control." },
  { author: "Epicteto", text: "Cuando alguien te provoque, recuerda que es tu juicio el que te provoca." },
  { author: "Epicteto", text: "Es imposible para un hombre aprender lo que cree que ya sabe." },
  { author: "Epicteto", text: "Lleva contigo estos pensamientos en todo momento: ¿qué es mío y qué no lo es?" },
  { author: "Epicteto", text: "No busques que los hechos se ajusten a tus deseos; ajusta tus deseos a los hechos." },
  { author: "Epicteto", text: "El material del bien y del mal está en nuestra propia elección." },
  { author: "Epicteto", text: "Si te dicen que hablan mal de ti, no te defiendas: di «no conocen mis otros defectos»." },
  { author: "Epicteto", text: "La libertad se compra con la renuncia a lo que no depende de nosotros." },
  { author: "Epicteto", text: "Examina tus impresiones como un portero examina a quien llama a la puerta." },
  { author: "Epicteto", text: "No digas «he perdido algo», di «lo he devuelto»." },
  { author: "Epicteto", text: "Practica, no solo leas. El atleta no se hace leyendo sobre el estadio." },
  { author: "Epicteto", text: "Quien se ríe de sí mismo no teme la burla ajena." },
  { author: "Musonio Rufo", text: "La práctica vale más que la teoría si de verdad quieres mejorar." },
  { author: "Musonio Rufo", text: "La virtud no es solo conocimiento: es acción habitual." },
  { author: "Musonio Rufo", text: "El lujo debilita; la frugalidad entrena el alma." },
  { author: "Musonio Rufo", text: "No hay excusa para no practicar la justicia cada día." },
  { author: "Musonio Rufo", text: "El cuerpo es instrumento; no lo conviertas en tirano." },
  { author: "Cleantes", text: "Lidera, oh Zeus, y tú, Destino; a donde me guíen, os seguiré sin dudar." },
  { author: "Cleantes", text: "Si no quiero seguir al destino de grado, lo haré a la fuerza y con menos dignidad." },
  { author: "Zenón de Citio", text: "El hombre tiene dos oídos y una boca para oír el doble de lo que habla." },
  { author: "Zenón de Citio", text: "La meta es vivir de acuerdo con la naturaleza." },
  { author: "Crisipo", text: "El sabio nada hace de lo que se arrepiente." },
  { author: "Crisipo", text: "El destino mueve el hilo; la virtud mueve la respuesta." },
  { author: "Hierocles", text: "Cada uno de nosotros es el centro de muchos círculos de deber." },
  { author: "Hierocles", text: "Extiende la preocupación desde ti hacia la familia, la ciudad y el género humano." },
  { author: "Marco Aurelio", text: "Hoy acepta tu juicio, porque el tiempo no espera." },
  { author: "Séneca", text: "Estoico del día: examina tu juicio antes de que el día se esfume." },
  { author: "Epicteto", text: "Que no se te escape: domina tu juicio, como si fuera tu último ensayo." },
  { author: "Musonio Rufo", text: "Observa tu juicio sin pedir que el mundo cambie primero." },
  { author: "Cleantes", text: "En silencio, elige tu juicio — y deja lo demás al destino." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, practica tu juicio, con la serenidad del sabio." },
  { author: "Crisipo", text: "Hoy recuerda tu juicio, en lugar de pelear con lo que no controlas." },
  { author: "Hierocles", text: "Estoico del día: suaviza tu juicio y verás que el alma se aligera." },
  { author: "Marco Aurelio", text: "Que no se te escape: fortalece tu juicio, aunque nadie te observe." },
  { author: "Séneca", text: "Ordena tu juicio como un ciudadano del cosmos." },
  { author: "Epicteto", text: "En silencio, acepta tus deseos — sin dramatizar la impresión." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, examina tus deseos, y vuelve a la acción recta." },
  { author: "Cleantes", text: "Hoy domina tus deseos, hoy, no mañana." },
  { author: "Zenón de Citio", text: "Estoico del día: observa tus deseos con mesura y coraje." },
  { author: "Crisipo", text: "Que no se te escape: elige tus deseos, recordando tu mortalidad." },
  { author: "Hierocles", text: "Practica tus deseos porque el tiempo no espera." },
  { author: "Marco Aurelio", text: "En silencio, recuerda tus deseos — antes de que el día se esfume." },
  { author: "Séneca", text: "Como un guardián de la razón, suaviza tus deseos, como si fuera tu último ensayo." },
  { author: "Epicteto", text: "Hoy fortalece tus deseos, sin pedir que el mundo cambie primero." },
  { author: "Musonio Rufo", text: "Estoico del día: ordena tus deseos y deja lo demás al destino." },
  { author: "Cleantes", text: "Que no se te escape: acepta tu miedo, con la serenidad del sabio." },
  { author: "Zenón de Citio", text: "Examina tu miedo en lugar de pelear con lo que no controlas." },
  { author: "Crisipo", text: "En silencio, domina tu miedo — y verás que el alma se aligera." },
  { author: "Hierocles", text: "Como un guardián de la razón, observa tu miedo, aunque nadie te observe." },
  { author: "Marco Aurelio", text: "Hoy elige tu miedo, como un ciudadano del cosmos." },
  { author: "Séneca", text: "Estoico del día: practica tu miedo sin dramatizar la impresión." },
  { author: "Epicteto", text: "Que no se te escape: recuerda tu miedo, y vuelve a la acción recta." },
  { author: "Musonio Rufo", text: "Suaviza tu miedo hoy, no mañana." },
  { author: "Cleantes", text: "En silencio, fortalece tu miedo — con mesura y coraje." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, ordena tu miedo, recordando tu mortalidad." },
  { author: "Crisipo", text: "Hoy acepta tu ira, porque el tiempo no espera." },
  { author: "Hierocles", text: "Estoico del día: examina tu ira antes de que el día se esfume." },
  { author: "Marco Aurelio", text: "Que no se te escape: domina tu ira, como si fuera tu último ensayo." },
  { author: "Séneca", text: "Observa tu ira sin pedir que el mundo cambie primero." },
  { author: "Epicteto", text: "En silencio, elige tu ira — y deja lo demás al destino." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, practica tu ira, con la serenidad del sabio." },
  { author: "Cleantes", text: "Hoy recuerda tu ira, en lugar de pelear con lo que no controlas." },
  { author: "Zenón de Citio", text: "Estoico del día: suaviza tu ira y verás que el alma se aligera." },
  { author: "Crisipo", text: "Que no se te escape: fortalece tu ira, aunque nadie te observe." },
  { author: "Hierocles", text: "Ordena tu ira como un ciudadano del cosmos." },
  { author: "Marco Aurelio", text: "En silencio, acepta tu prisa — sin dramatizar la impresión." },
  { author: "Séneca", text: "Como un guardián de la razón, examina tu prisa, y vuelve a la acción recta." },
  { author: "Epicteto", text: "Hoy domina tu prisa, hoy, no mañana." },
  { author: "Musonio Rufo", text: "Estoico del día: observa tu prisa con mesura y coraje." },
  { author: "Cleantes", text: "Que no se te escape: elige tu prisa, recordando tu mortalidad." },
  { author: "Zenón de Citio", text: "Practica tu prisa porque el tiempo no espera." },
  { author: "Crisipo", text: "En silencio, recuerda tu prisa — antes de que el día se esfume." },
  { author: "Hierocles", text: "Como un guardián de la razón, suaviza tu prisa, como si fuera tu último ensayo." },
  { author: "Marco Aurelio", text: "Hoy fortalece tu prisa, sin pedir que el mundo cambie primero." },
  { author: "Séneca", text: "Estoico del día: ordena tu prisa y deja lo demás al destino." },
  { author: "Epicteto", text: "Que no se te escape: acepta tu lengua, con la serenidad del sabio." },
  { author: "Musonio Rufo", text: "Examina tu lengua en lugar de pelear con lo que no controlas." },
  { author: "Cleantes", text: "En silencio, domina tu lengua — y verás que el alma se aligera." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, observa tu lengua, aunque nadie te observe." },
  { author: "Crisipo", text: "Hoy elige tu lengua, como un ciudadano del cosmos." },
  { author: "Hierocles", text: "Estoico del día: practica tu lengua sin dramatizar la impresión." },
  { author: "Marco Aurelio", text: "Que no se te escape: recuerda tu lengua, y vuelve a la acción recta." },
  { author: "Séneca", text: "Suaviza tu lengua hoy, no mañana." },
  { author: "Epicteto", text: "En silencio, fortalece tu lengua — con mesura y coraje." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, ordena tu lengua, recordando tu mortalidad." },
  { author: "Cleantes", text: "Hoy acepta tu atención, porque el tiempo no espera." },
  { author: "Zenón de Citio", text: "Estoico del día: examina tu atención antes de que el día se esfume." },
  { author: "Crisipo", text: "Que no se te escape: domina tu atención, como si fuera tu último ensayo." },
  { author: "Hierocles", text: "Observa tu atención sin pedir que el mundo cambie primero." },
  { author: "Marco Aurelio", text: "En silencio, elige tu atención — y deja lo demás al destino." },
  { author: "Séneca", text: "Como un guardián de la razón, practica tu atención, con la serenidad del sabio." },
  { author: "Epicteto", text: "Hoy recuerda tu atención, en lugar de pelear con lo que no controlas." },
  { author: "Musonio Rufo", text: "Estoico del día: suaviza tu atención y verás que el alma se aligera." },
  { author: "Cleantes", text: "Que no se te escape: fortalece tu atención, aunque nadie te observe." },
  { author: "Zenón de Citio", text: "Ordena tu atención como un ciudadano del cosmos." },
  { author: "Crisipo", text: "En silencio, acepta tu deber — sin dramatizar la impresión." },
  { author: "Hierocles", text: "Como un guardián de la razón, examina tu deber, y vuelve a la acción recta." },
  { author: "Marco Aurelio", text: "Hoy domina tu deber, hoy, no mañana." },
  { author: "Séneca", text: "Estoico del día: observa tu deber con mesura y coraje." },
  { author: "Epicteto", text: "Que no se te escape: elige tu deber, recordando tu mortalidad." },
  { author: "Musonio Rufo", text: "Practica tu deber porque el tiempo no espera." },
  { author: "Cleantes", text: "En silencio, recuerda tu deber — antes de que el día se esfume." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, suaviza tu deber, como si fuera tu último ensayo." },
  { author: "Crisipo", text: "Hoy fortalece tu deber, sin pedir que el mundo cambie primero." },
  { author: "Hierocles", text: "Estoico del día: ordena tu deber y deja lo demás al destino." },
  { author: "Marco Aurelio", text: "Que no se te escape: acepta tu carácter, con la serenidad del sabio." },
  { author: "Séneca", text: "Examina tu carácter en lugar de pelear con lo que no controlas." },
  { author: "Epicteto", text: "En silencio, domina tu carácter — y verás que el alma se aligera." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, observa tu carácter, aunque nadie te observe." },
  { author: "Cleantes", text: "Hoy elige tu carácter, como un ciudadano del cosmos." },
  { author: "Zenón de Citio", text: "Estoico del día: practica tu carácter sin dramatizar la impresión." },
  { author: "Crisipo", text: "Que no se te escape: recuerda tu carácter, y vuelve a la acción recta." },
  { author: "Hierocles", text: "Suaviza tu carácter hoy, no mañana." },
  { author: "Marco Aurelio", text: "En silencio, fortalece tu carácter — con mesura y coraje." },
  { author: "Séneca", text: "Como un guardián de la razón, ordena tu carácter, recordando tu mortalidad." },
  { author: "Epicteto", text: "Hoy acepta tu respiración, porque el tiempo no espera." },
  { author: "Musonio Rufo", text: "Estoico del día: examina tu respiración antes de que el día se esfume." },
  { author: "Cleantes", text: "Que no se te escape: domina tu respiración, como si fuera tu último ensayo." },
  { author: "Zenón de Citio", text: "Observa tu respiración sin pedir que el mundo cambie primero." },
  { author: "Crisipo", text: "En silencio, elige tu respiración — y deja lo demás al destino." },
  { author: "Hierocles", text: "Como un guardián de la razón, practica tu respiración, con la serenidad del sabio." },
  { author: "Marco Aurelio", text: "Hoy recuerda tu respiración, en lugar de pelear con lo que no controlas." },
  { author: "Séneca", text: "Estoico del día: suaviza tu respiración y verás que el alma se aligera." },
  { author: "Epicteto", text: "Que no se te escape: fortalece tu respiración, aunque nadie te observe." },
  { author: "Musonio Rufo", text: "Ordena tu respiración como un ciudadano del cosmos." },
  { author: "Cleantes", text: "En silencio, acepta el presente — sin dramatizar la impresión." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, examina el presente, y vuelve a la acción recta." },
  { author: "Crisipo", text: "Hoy domina el presente, hoy, no mañana." },
  { author: "Hierocles", text: "Estoico del día: observa el presente con mesura y coraje." },
  { author: "Marco Aurelio", text: "Que no se te escape: elige el presente, recordando tu mortalidad." },
  { author: "Séneca", text: "Practica el presente porque el tiempo no espera." },
  { author: "Epicteto", text: "En silencio, recuerda el presente — antes de que el día se esfume." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, suaviza el presente, como si fuera tu último ensayo." },
  { author: "Cleantes", text: "Hoy fortalece el presente, sin pedir que el mundo cambie primero." },
  { author: "Zenón de Citio", text: "Estoico del día: ordena el presente y deja lo demás al destino." },
  { author: "Crisipo", text: "Que no se te escape: acepta lo inevitable, con la serenidad del sabio." },
  { author: "Hierocles", text: "Examina lo inevitable en lugar de pelear con lo que no controlas." },
  { author: "Marco Aurelio", text: "En silencio, domina lo inevitable — y verás que el alma se aligera." },
  { author: "Séneca", text: "Como un guardián de la razón, observa lo inevitable, aunque nadie te observe." },
  { author: "Epicteto", text: "Hoy elige lo inevitable, como un ciudadano del cosmos." },
  { author: "Musonio Rufo", text: "Estoico del día: practica lo inevitable sin dramatizar la impresión." },
  { author: "Cleantes", text: "Que no se te escape: recuerda lo inevitable, y vuelve a la acción recta." },
  { author: "Zenón de Citio", text: "Suaviza lo inevitable hoy, no mañana." },
  { author: "Crisipo", text: "En silencio, fortalece lo inevitable — con mesura y coraje." },
  { author: "Hierocles", text: "Como un guardián de la razón, ordena lo inevitable, recordando tu mortalidad." },
  { author: "Marco Aurelio", text: "Hoy acepta la fortuna, porque el tiempo no espera." },
  { author: "Séneca", text: "Estoico del día: examina la fortuna antes de que el día se esfume." },
  { author: "Epicteto", text: "Que no se te escape: domina la fortuna, como si fuera tu último ensayo." },
  { author: "Musonio Rufo", text: "Observa la fortuna sin pedir que el mundo cambie primero." },
  { author: "Cleantes", text: "En silencio, elige la fortuna — y deja lo demás al destino." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, practica la fortuna, con la serenidad del sabio." },
  { author: "Crisipo", text: "Hoy recuerda la fortuna, en lugar de pelear con lo que no controlas." },
  { author: "Hierocles", text: "Estoico del día: suaviza la fortuna y verás que el alma se aligera." },
  { author: "Marco Aurelio", text: "Que no se te escape: fortalece la fortuna, aunque nadie te observe." },
  { author: "Séneca", text: "Ordena la fortuna como un ciudadano del cosmos." },
  { author: "Epicteto", text: "En silencio, acepta el dolor breve — sin dramatizar la impresión." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, examina el dolor breve, y vuelve a la acción recta." },
  { author: "Cleantes", text: "Hoy domina el dolor breve, hoy, no mañana." },
  { author: "Zenón de Citio", text: "Estoico del día: observa el dolor breve con mesura y coraje." },
  { author: "Crisipo", text: "Que no se te escape: elige el dolor breve, recordando tu mortalidad." },
  { author: "Hierocles", text: "Practica el dolor breve porque el tiempo no espera." },
  { author: "Marco Aurelio", text: "En silencio, recuerda el dolor breve — antes de que el día se esfume." },
  { author: "Séneca", text: "Como un guardián de la razón, suaviza el dolor breve, como si fuera tu último ensayo." },
  { author: "Epicteto", text: "Hoy fortalece el dolor breve, sin pedir que el mundo cambie primero." },
  { author: "Musonio Rufo", text: "Estoico del día: ordena el dolor breve y deja lo demás al destino." },
  { author: "Cleantes", text: "Que no se te escape: acepta la fama hueca, con la serenidad del sabio." },
  { author: "Zenón de Citio", text: "Examina la fama hueca en lugar de pelear con lo que no controlas." },
  { author: "Crisipo", text: "En silencio, domina la fama hueca — y verás que el alma se aligera." },
  { author: "Hierocles", text: "Como un guardián de la razón, observa la fama hueca, aunque nadie te observe." },
  { author: "Marco Aurelio", text: "Hoy elige la fama hueca, como un ciudadano del cosmos." },
  { author: "Séneca", text: "Estoico del día: practica la fama hueca sin dramatizar la impresión." },
  { author: "Epicteto", text: "Que no se te escape: recuerda la fama hueca, y vuelve a la acción recta." },
  { author: "Musonio Rufo", text: "Suaviza la fama hueca hoy, no mañana." },
  { author: "Cleantes", text: "En silencio, fortalece la fama hueca — con mesura y coraje." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, ordena la fama hueca, recordando tu mortalidad." },
  { author: "Crisipo", text: "Hoy acepta el apego, porque el tiempo no espera." },
  { author: "Hierocles", text: "Estoico del día: examina el apego antes de que el día se esfume." },
  { author: "Marco Aurelio", text: "Que no se te escape: domina el apego, como si fuera tu último ensayo." },
  { author: "Séneca", text: "Observa el apego sin pedir que el mundo cambie primero." },
  { author: "Epicteto", text: "En silencio, elige el apego — y deja lo demás al destino." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, practica el apego, con la serenidad del sabio." },
  { author: "Cleantes", text: "Hoy recuerda el apego, en lugar de pelear con lo que no controlas." },
  { author: "Zenón de Citio", text: "Estoico del día: suaviza el apego y verás que el alma se aligera." },
  { author: "Crisipo", text: "Que no se te escape: fortalece el apego, aunque nadie te observe." },
  { author: "Hierocles", text: "Ordena el apego como un ciudadano del cosmos." },
  { author: "Marco Aurelio", text: "En silencio, acepta la queja — sin dramatizar la impresión." },
  { author: "Séneca", text: "Como un guardián de la razón, examina la queja, y vuelve a la acción recta." },
  { author: "Epicteto", text: "Hoy domina la queja, hoy, no mañana." },
  { author: "Musonio Rufo", text: "Estoico del día: observa la queja con mesura y coraje." },
  { author: "Cleantes", text: "Que no se te escape: elige la queja, recordando tu mortalidad." },
  { author: "Zenón de Citio", text: "Practica la queja porque el tiempo no espera." },
  { author: "Crisipo", text: "En silencio, recuerda la queja — antes de que el día se esfume." },
  { author: "Hierocles", text: "Como un guardián de la razón, suaviza la queja, como si fuera tu último ensayo." },
  { author: "Marco Aurelio", text: "Hoy fortalece la queja, sin pedir que el mundo cambie primero." },
  { author: "Séneca", text: "Estoico del día: ordena la queja y deja lo demás al destino." },
  { author: "Epicteto", text: "Que no se te escape: acepta la envidia, con la serenidad del sabio." },
  { author: "Musonio Rufo", text: "Examina la envidia en lugar de pelear con lo que no controlas." },
  { author: "Cleantes", text: "En silencio, domina la envidia — y verás que el alma se aligera." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, observa la envidia, aunque nadie te observe." },
  { author: "Crisipo", text: "Hoy elige la envidia, como un ciudadano del cosmos." },
  { author: "Hierocles", text: "Estoico del día: practica la envidia sin dramatizar la impresión." },
  { author: "Marco Aurelio", text: "Que no se te escape: recuerda la envidia, y vuelve a la acción recta." },
  { author: "Séneca", text: "Suaviza la envidia hoy, no mañana." },
  { author: "Epicteto", text: "En silencio, fortalece la envidia — con mesura y coraje." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, ordena la envidia, recordando tu mortalidad." },
  { author: "Cleantes", text: "Hoy acepta la vanidad, porque el tiempo no espera." },
  { author: "Zenón de Citio", text: "Estoico del día: examina la vanidad antes de que el día se esfume." },
  { author: "Crisipo", text: "Que no se te escape: domina la vanidad, como si fuera tu último ensayo." },
  { author: "Hierocles", text: "Observa la vanidad sin pedir que el mundo cambie primero." },
  { author: "Marco Aurelio", text: "En silencio, elige la vanidad — y deja lo demás al destino." },
  { author: "Séneca", text: "Como un guardián de la razón, practica la vanidad, con la serenidad del sabio." },
  { author: "Epicteto", text: "Hoy recuerda la vanidad, en lugar de pelear con lo que no controlas." },
  { author: "Musonio Rufo", text: "Estoico del día: suaviza la vanidad y verás que el alma se aligera." },
  { author: "Cleantes", text: "Que no se te escape: fortalece la vanidad, aunque nadie te observe." },
  { author: "Zenón de Citio", text: "Ordena la vanidad como un ciudadano del cosmos." },
  { author: "Crisipo", text: "En silencio, acepta el exceso — sin dramatizar la impresión." },
  { author: "Hierocles", text: "Como un guardián de la razón, examina el exceso, y vuelve a la acción recta." },
  { author: "Marco Aurelio", text: "Hoy domina el exceso, hoy, no mañana." },
  { author: "Séneca", text: "Estoico del día: observa el exceso con mesura y coraje." },
  { author: "Epicteto", text: "Que no se te escape: elige el exceso, recordando tu mortalidad." },
  { author: "Musonio Rufo", text: "Practica el exceso porque el tiempo no espera." },
  { author: "Cleantes", text: "En silencio, recuerda el exceso — antes de que el día se esfume." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, suaviza el exceso, como si fuera tu último ensayo." },
  { author: "Crisipo", text: "Hoy fortalece el exceso, sin pedir que el mundo cambie primero." },
  { author: "Hierocles", text: "Estoico del día: ordena el exceso y deja lo demás al destino." },
  { author: "Marco Aurelio", text: "Que no se te escape: acepta tu juicio, con la serenidad del sabio." },
  { author: "Séneca", text: "Examina tu juicio en lugar de pelear con lo que no controlas." },
  { author: "Epicteto", text: "En silencio, domina tu juicio — y verás que el alma se aligera." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, observa tu juicio, aunque nadie te observe." },
  { author: "Cleantes", text: "Hoy elige tu juicio, como un ciudadano del cosmos." },
  { author: "Zenón de Citio", text: "Estoico del día: practica tu juicio sin dramatizar la impresión." },
  { author: "Crisipo", text: "Que no se te escape: recuerda tu juicio, y vuelve a la acción recta." },
  { author: "Hierocles", text: "Suaviza tu juicio hoy, no mañana." },
  { author: "Marco Aurelio", text: "En silencio, fortalece tu juicio — con mesura y coraje." },
  { author: "Séneca", text: "Como un guardián de la razón, ordena tu juicio, recordando tu mortalidad." },
  { author: "Epicteto", text: "Hoy acepta tus deseos, porque el tiempo no espera." },
  { author: "Musonio Rufo", text: "Estoico del día: examina tus deseos antes de que el día se esfume." },
  { author: "Cleantes", text: "Que no se te escape: domina tus deseos, como si fuera tu último ensayo." },
  { author: "Zenón de Citio", text: "Observa tus deseos sin pedir que el mundo cambie primero." },
  { author: "Crisipo", text: "En silencio, elige tus deseos — y deja lo demás al destino." },
  { author: "Hierocles", text: "Como un guardián de la razón, practica tus deseos, con la serenidad del sabio." },
  { author: "Marco Aurelio", text: "Hoy recuerda tus deseos, en lugar de pelear con lo que no controlas." },
  { author: "Séneca", text: "Estoico del día: suaviza tus deseos y verás que el alma se aligera." },
  { author: "Epicteto", text: "Que no se te escape: fortalece tus deseos, aunque nadie te observe." },
  { author: "Musonio Rufo", text: "Ordena tus deseos como un ciudadano del cosmos." },
  { author: "Cleantes", text: "En silencio, acepta tu miedo — sin dramatizar la impresión." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, examina tu miedo, y vuelve a la acción recta." },
  { author: "Crisipo", text: "Hoy domina tu miedo, hoy, no mañana." },
  { author: "Hierocles", text: "Estoico del día: observa tu miedo con mesura y coraje." },
  { author: "Marco Aurelio", text: "Que no se te escape: elige tu miedo, recordando tu mortalidad." },
  { author: "Séneca", text: "Practica tu miedo porque el tiempo no espera." },
  { author: "Epicteto", text: "En silencio, recuerda tu miedo — antes de que el día se esfume." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, suaviza tu miedo, como si fuera tu último ensayo." },
  { author: "Cleantes", text: "Hoy fortalece tu miedo, sin pedir que el mundo cambie primero." },
  { author: "Zenón de Citio", text: "Estoico del día: ordena tu miedo y deja lo demás al destino." },
  { author: "Crisipo", text: "Que no se te escape: acepta tu ira, con la serenidad del sabio." },
  { author: "Hierocles", text: "Examina tu ira en lugar de pelear con lo que no controlas." },
  { author: "Marco Aurelio", text: "En silencio, domina tu ira — y verás que el alma se aligera." },
  { author: "Séneca", text: "Como un guardián de la razón, observa tu ira, aunque nadie te observe." },
  { author: "Epicteto", text: "Hoy elige tu ira, como un ciudadano del cosmos." },
  { author: "Musonio Rufo", text: "Estoico del día: practica tu ira sin dramatizar la impresión." },
  { author: "Cleantes", text: "Que no se te escape: recuerda tu ira, y vuelve a la acción recta." },
  { author: "Zenón de Citio", text: "Suaviza tu ira hoy, no mañana." },
  { author: "Crisipo", text: "En silencio, fortalece tu ira — con mesura y coraje." },
  { author: "Hierocles", text: "Como un guardián de la razón, ordena tu ira, recordando tu mortalidad." },
  { author: "Marco Aurelio", text: "Hoy acepta tu prisa, porque el tiempo no espera." },
  { author: "Séneca", text: "Estoico del día: examina tu prisa antes de que el día se esfume." },
  { author: "Epicteto", text: "Que no se te escape: domina tu prisa, como si fuera tu último ensayo." },
  { author: "Musonio Rufo", text: "Observa tu prisa sin pedir que el mundo cambie primero." },
  { author: "Cleantes", text: "En silencio, elige tu prisa — y deja lo demás al destino." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, practica tu prisa, con la serenidad del sabio." },
  { author: "Crisipo", text: "Hoy recuerda tu prisa, en lugar de pelear con lo que no controlas." },
  { author: "Hierocles", text: "Estoico del día: suaviza tu prisa y verás que el alma se aligera." },
  { author: "Marco Aurelio", text: "Que no se te escape: fortalece tu prisa, aunque nadie te observe." },
  { author: "Séneca", text: "Ordena tu prisa como un ciudadano del cosmos." },
  { author: "Epicteto", text: "En silencio, acepta tu lengua — sin dramatizar la impresión." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, examina tu lengua, y vuelve a la acción recta." },
  { author: "Cleantes", text: "Hoy domina tu lengua, hoy, no mañana." },
  { author: "Zenón de Citio", text: "Estoico del día: observa tu lengua con mesura y coraje." },
  { author: "Crisipo", text: "Que no se te escape: elige tu lengua, recordando tu mortalidad." },
  { author: "Hierocles", text: "Practica tu lengua porque el tiempo no espera." },
  { author: "Marco Aurelio", text: "En silencio, recuerda tu lengua — antes de que el día se esfume." },
  { author: "Séneca", text: "Como un guardián de la razón, suaviza tu lengua, como si fuera tu último ensayo." },
  { author: "Epicteto", text: "Hoy fortalece tu lengua, sin pedir que el mundo cambie primero." },
  { author: "Musonio Rufo", text: "Estoico del día: ordena tu lengua y deja lo demás al destino." },
  { author: "Cleantes", text: "Que no se te escape: acepta tu atención, con la serenidad del sabio." },
  { author: "Zenón de Citio", text: "Examina tu atención en lugar de pelear con lo que no controlas." },
  { author: "Crisipo", text: "En silencio, domina tu atención — y verás que el alma se aligera." },
  { author: "Hierocles", text: "Como un guardián de la razón, observa tu atención, aunque nadie te observe." },
  { author: "Marco Aurelio", text: "Hoy elige tu atención, como un ciudadano del cosmos." },
  { author: "Séneca", text: "Estoico del día: practica tu atención sin dramatizar la impresión." },
  { author: "Epicteto", text: "Que no se te escape: recuerda tu atención, y vuelve a la acción recta." },
  { author: "Musonio Rufo", text: "Suaviza tu atención hoy, no mañana." },
  { author: "Cleantes", text: "En silencio, fortalece tu atención — con mesura y coraje." },
  { author: "Zenón de Citio", text: "Como un guardián de la razón, ordena tu atención, recordando tu mortalidad." },
  { author: "Crisipo", text: "Hoy acepta tu deber, porque el tiempo no espera." },
  { author: "Hierocles", text: "Estoico del día: examina tu deber antes de que el día se esfume." },
  { author: "Marco Aurelio", text: "Que no se te escape: domina tu deber, como si fuera tu último ensayo." },
  { author: "Séneca", text: "Observa tu deber sin pedir que el mundo cambie primero." },
  { author: "Epicteto", text: "En silencio, elige tu deber — y deja lo demás al destino." },
  { author: "Musonio Rufo", text: "Como un guardián de la razón, practica tu deber, con la serenidad del sabio." },
  { author: "Cleantes", text: "Hoy recuerda tu deber, en lugar de pelear con lo que no controlas." },
  { author: "Zenón de Citio", text: "Estoico del día: suaviza tu deber y verás que el alma se aligera." },
  { author: "Crisipo", text: "Que no se te escape: fortalece tu deber, aunque nadie te observe." },
  { author: "Hierocles", text: "Ordena tu deber como un ciudadano del cosmos." },
  { author: "Marco Aurelio", text: "En silencio, acepta tu carácter — sin dramatizar la impresión." },
  { author: "Séneca", text: "Como un guardián de la razón, examina tu carácter, y vuelve a la acción recta." },
  { author: "Epicteto", text: "Hoy domina tu carácter, hoy, no mañana." },
  { author: "Musonio Rufo", text: "Estoico del día: observa tu carácter con mesura y coraje." },
  { author: "Cleantes", text: "Que no se te escape: elige tu carácter, recordando tu mortalidad." },
  { author: "Zenón de Citio", text: "Practica tu carácter porque el tiempo no espera." },
  { author: "Crisipo", text: "En silencio, recuerda tu carácter — antes de que el día se esfume." },
  { author: "Hierocles", text: "Como un guardián de la razón, suaviza tu carácter, como si fuera tu último ensayo." },
  { author: "Marco Aurelio", text: "Hoy fortalece tu carácter, sin pedir que el mundo cambie primero." },
  { author: "Séneca", text: "Estoico del día: ordena tu carácter y deja lo demás al destino." },
  { author: "Epicteto", text: "Que no se te escape: acepta tu respiración, con la serenidad del sabio." },
  { author: "Musonio Rufo", text: "Examina tu respiración en lugar de pelear con lo que no controlas." },
];

export function dayOfYear(date = new Date()): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  return Math.floor(diff / 86_400_000);
}

/** Frase del día (1–365; 366 de año bisiesto reutiliza la 365). */
export function getStoicQuoteForDate(date = new Date()): StoicQuote {
  const d = dayOfYear(date);
  const idx = Math.min(Math.max(d, 1), 365) - 1;
  return STOIC_QUOTES[idx] ?? STOIC_QUOTES[0];
}
